### ISSUE TITLE
A suggestion about "Installing the SDK" tutorial

### ISSUE THREAD

**Issue by changbenny** [ringcentral/ringcentral.github.io#19]
In the [part of "Installing the SDK"](http://ringcentral.github.io/tutorial/?javascript#installing-the-sdk), the tutorial suggests developers read our instructions on GitHub. I think the tutorial can provide the simplest way to install the SDK (Using CDN or Bower for our bundled SDK files). If developers want to check the completed installation methods, they can go to our GitHub page.

What do you think about this modification? Thanks.

**Comment by grokify** [comment]
Using a CDN for the JS SDK is something we want to do and will add when it is ready.

The Bower install is straight-forward enough that it can be added. Please feel free to send a PR and we'll get this in.

**Comment by changbenny** [comment]
Ok, I will check out the ringcentral/slate repo.
